traefik:
  wildcardHostname: "*.juhmertena.com"
  hostnames:
    dashboard: traefik-dashboard.juhmertena.com
    roller: saorpg-roller.juhmertena.com
  certManager:
    issuer: origin-ca
    originCAIssuer:
      enabled: true

externalDns:
  enabled: true

developmentDatabase:
  enabled: false

images:
  registry: registry.digitalocean.com/saorpg-roller-registry
  backend:
    repository: saorpg-roller-backend
    tag: 1.0.0-alpha.1
  frontend:
    repository: saorpg-roller-frontend
    tag: 1.0.0-alpha.1
  sqitch:
    repository: saorpg-roller-sqitch
    tag: 1.0.0-alpha.1
