traefik:
  wildcardHostname: "*.juhmertena.com"
  hostnames:
    dashboard: traefik-dashboard.juhmertena.com
  certManager:
    issuer: origin-ca
    originCAIssuer:
      enabled: true

externalDns:
  enabled: true

developmentDatabase:
  enabled: false
