apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: saorpg-roller
  labels:
    app: saorpg-roller
spec:
  parentRefs:
  - name: traefik-gateway
    namespace: "{{ .Values.namespace.traefik }}"
    sectionName: websecure
  hostnames:
  - "{{ .Values.traefik.hostnames.roller }}"
  rules:
  - backendRefs:
    - name: "saorpg-roller-frontend"
      port: 80
    