apiVersion: apps/v1
kind: Deployment
metadata:
  name: saorpg-roller-backend
  labels:
    app: saorpg-roller-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: saorpg-roller-backend
  template:
    metadata:
      labels: 
        app: saorpg-roller-backend
    spec:
      containers:
        - name: saorpg-roller-backend
          image: {{ include "saorpg-roller.image-name" (dict "Values" .Values "Image" .Values.images.backend) }}
          ports:
            - containerPort: 8080
              name: http-api
          env:
          - name: DATABASE_JDBC_URI
            valueFrom:
              secretKeyRef:
                name: saorpg-roller-secrets
                key: jdbcUri
      initContainers:
      - name: sqitch-db-migration
        image: {{ include "saorpg-roller.image-name" (dict "Values" .Values "Image" .Values.images.sqitch) }}
        # Needed so that the sqitch container can use the DATABASE_URI Secret
        command: ["/bin/sh"]
        args: ["-c", "sqitch deploy --target ${DATABASE_URI}"]
        env:
          - name: DATABASE_URI
            valueFrom:
              secretKeyRef:
                name: saorpg-roller-secrets
                key: database-uri
