apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: saorpg-roller-backend
  labels:
    app: saorpg-roller-backend
spec:
  parentRefs:
  - name: traefik-gateway
    namespace: "{{ .Values.namespace.traefik }}"
    sectionName: websecure
  hostnames:
  - "{{ .Values.traefik.hostnames.roller }}"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /api
    backendRefs:
    - name: saorpg-roller-backend
      port: 80
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: /
