apiVersion: v1
kind: Secret
metadata:
  name: saorpg-roller-secrets
type: Opaque
data:
  database-uri: {{ .Values.postgres.uri | b64enc | quote }}
  jdbcUri: {{ .Values.postgres.jdbcUri | b64enc | quote }}
