apiVersion: v1
kind: Service
metadata:
  name: saorpg-roller-backend
  labels:
    app: saorpg-roller-backend
spec:
  type: ClusterIP
  selector:
    app: saorpg-roller-backend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http-api
