{{- range $namespace, $_ := .Values.pushSecrets }}
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ include "shared-secrets.k8sSecretStoreName" (list $ $namespace) }}
  labels:
    {{- include "shared-secrets.labels" $ | nindent 4 }}
spec:
  provider:
    kubernetes:
      # with this, the store is able to pull only from `default` namespace
      remoteNamespace: {{ $namespace }}
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        serviceAccount:
          name: {{ include "shared-secrets.serviceAccountName" $ }}
{{- end }}
