apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: saorpg-roller-frontend
  labels:
    app: saorpg-roller-frontend
spec:
  parentRefs:
  - name: traefik-gateway
    namespace: "{{ .Values.namespace.traefik }}"
    sectionName: websecure
  hostnames:
  - "{{ .Values.traefik.hostnames.roller }}"
  rules:
  - matches:
      - path:
          type: PathPrefix
          value: /
    backendRefs:
    - name: saorpg-roller-frontend
      port: 80
