apiVersion: v1
kind: Service
metadata:
  name: saorpg-roller-frontend
  labels:
    app: saorpg-roller-frontend
spec:
  type: ClusterIP
  selector:
    app: saorpg-roller-frontend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http-webapp
