{{- range $name, $spec := .Values.externalSecrets }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $name }}
spec:
  secretStoreRef:
    name: {{ include "shared-secrets.awsSecretStoreName" $ }}
    kind: SecretStore
  {{- $spec | toYaml | nindent 2}}
{{- end }}
