{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "shared-secrets.serviceAccountName" . }}
  labels:
    {{- include "shared-secrets.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "shared-secrets.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "shared-secrets.roleName" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
