traefik:
  wildcardHostname: "*.docker.localhost"
  hostnames:
    dashboard: traefik-dashboard.docker.localhost
    roller: saorpg-roller.docker.localhost
  certManager:
    issuer: self-signed
    originCAIssuer:
      enabled: false

externalDns:
  enabled: false

developmentDatabase:
  enabled: true

images:
  # Pretty much the local reigistry
  registry: docker.io
  backend:
    repository: saorpg/saorpg-roller-backend
    tag: 0.0.2-SNAPSHOT
  frontend:
    repository: saorpg/saorpg-roller-frontend
    tag: 0.0.1
  sqitch:
    repository: saorpg/saorpg-roller-sqitch
    tag: 0.0.1
